# Altair 소개

[Altair](https://altair-viz.github.io/)는 Python을 위한 선언적 통계 시각화 라이브러리입니다. Altair는 광범위한 통계 그래픽을 신속하게 구축할 수 있는 강력하고 간결한 시각화 문법을 제공합니다.

*선언적(declarative)*이라는 말은, for 루프나 저수준 그리기 명령 등 시각화를 *어떻게* 구현할지 명시하는 대신, *데이터*, *그래픽 마크*, *인코딩 채널*의 측면에서 시각화에 *무엇*을 포함하고 싶은지에 대한 고수준 사양을 제공할 수 있음을 의미합니다. 핵심 아이디어는 데이터 필드와 x축, y축, 색상 등과 같은 시각적 인코딩 채널 간의 연결을 선언한다는 것입니다. 나머지 플롯 세부 사항은 자동으로 처리됩니다. 이러한 선언적 플로팅 아이디어를 바탕으로 간결한 문법을 사용하여 단순한 시각화부터 정교한 시각화까지 놀라울 정도로 다양하게 만들 수 있습니다.

Altair는 대화형 그래픽의 고수준 문법인 [Vega-Lite](https://vega.github.io/vega-lite/)를 기반으로 합니다. Altair는 [JSON (JavaScript Object Notation)](https://en.wikipedia.org/wiki/JSON) 형식의 Vega-Lite 사양을 생성하는 친숙한 Python [API (Application Programming Interface)](https://en.wikipedia.org/wiki/Application_programming_interface)를 제공합니다. Jupyter Notebook, JupyterLab, Colab과 같은 환경에서는 이 사양을 가져와 웹 브라우저에서 직접 렌더링할 수 있습니다. Altair와 Vega-Lite의 동기와 기본 개념에 대해 자세히 알아보려면 [OpenVisConf 2017의 Vega-Lite 발표 영상](https://www.youtube.com/watch?v=9uaHRWj04D4)을 시청하세요.

이 노트북은 Altair에서 시각화를 만드는 기본 과정을 안내합니다. 먼저 Altair 패키지와 해당 종속성이 설치되어 있는지 확인하거나([Altair 설치 문서](https://altair-viz.github.io/getting_started/installation.html) 참조), 종속성이 사전 설치된 노트북 환경을 사용하고 있는지 확인해야 합니다.

_이 노트북은 [데이터 시각화 커리큘럼](https://github.com/uwdata/visualization-curriculum)의 일부입니다._

## 라이브러리 임포트

먼저 필요한 라이브러리인 데이터 프레임을 위한 Pandas와 시각화를 위한 Altair를 임포트해야 합니다.

In [1]:
import pandas as pd
import altair as alt

## 렌더러 (Renderers)

사용하는 환경에 따라 Altair를 위한 [렌더러](https://altair-viz.github.io/user_guide/display_frontends.html)를 지정해야 할 수도 있습니다. __JupyterLab__, __Jupyter Notebook__ 또는 인터넷에 연결된 __Google Colab__을 사용하는 경우 별도의 설정이 필요하지 않습니다. 그렇지 않은 경우 [Altair 차트 표시하기](https://altair-viz.github.io/user_guide/display_frontends.html) 문서를 읽어보세요.

## 데이터

Altair의 데이터는 명명된 데이터 *열(columns)*로 구성된 Pandas 데이터 프레임을 중심으로 구축됩니다. 또한 데이터 열을 데이터 *필드(fields)*라고도 부릅니다.

Altair를 사용할 때 데이터 세트는 일반적으로 데이터 프레임으로 제공됩니다. 또는 Altair는 네트워크를 통해 접근 가능한 데이터 세트를 로드하기 위한 URL을 허용할 수도 있습니다. 앞으로 보게 되겠지만, 데이터 프레임의 이름이 지정된 열은 Altair로 플로팅하는 데 필수적인 요소입니다.

우리는 종종 [vega-datasets](https://github.com/vega/vega-datasets) 저장소의 데이터 세트를 사용합니다. 이러한 데이터 세트 중 일부는 Pandas 데이터 프레임으로 직접 사용할 수 있습니다:

In [2]:
from vega_datasets import data  # vega_datasets 임포트
cars = data.cars()              # 자동차 데이터를 Pandas 데이터 프레임으로 로드
cars.head()                     # 처음 5행 표시

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA

vega-datasets 컬렉션의 데이터 세트는 URL을 통해 접근할 수도 있습니다:

In [3]:
data.cars.url

'https://vega.github.io/vega-datasets/data/cars.json'

데이터 세트 URL은 Altair에 직접 전달되거나(JSON 및 [CSV](https://en.wikipedia.org/wiki/Comma-separated_values)와 같이 지원되는 형식의 경우), 다음과 같이 Pandas 데이터 프레임으로 로드될 수 있습니다:

In [4]:
pd.read_json(data.cars.url).head() # JSON 데이터를 데이터 프레임으로 로드

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA

데이터 프레임에 대한 자세한 내용과 Altair로 플로팅하기 위해 Pandas 데이터 프레임을 준비하는 몇 가지 유용한 변환에 대해서는 [Altair로 데이터 지정하기 문서](https://altair-viz.github.io/user_guide/data.html)를 참조하세요.

### 날씨 데이터

Altair에서의 통계적 시각화는 ["tidy"](http://vita.had.co.nz/papers/tidy-data.html) 데이터 프레임에서 시작됩니다. 여기서는 특정 `도시(city)`와 `월(month)`에 대한 평균 `강수량(precip)`을 포함하는 간단한 데이터 프레임(`df`)을 만드는 것부터 시작해 보겠습니다:

In [5]:
df = pd.DataFrame({
    'city': ['서울', '서울', '서울', '부산', '부산', '부산', '제주', '제주', '제주'],
    'month': ['4월', '8월', '12월', '4월', '8월', '12월', '4월', '8월', '12월'],
    'precip': [2.68, 0.87, 5.31, 3.94, 4.13, 3.58, 3.62, 3.98, 2.56]
})

df

  city month  precip
0   서울   4월    2.68
1   서울   8월    0.87
2   서울  12월    5.31
3   부산   4월    3.94
4   부산   8월    4.13
5   부산  12월    3.58
6   제주   4월    3.62
7   제주   8월    3.98
8   제주  12월    2.56

## 차트 객체 (The Chart Object)

Altair의 기본 객체는 `Chart`로, 데이터 프레임을 단일 인수로 받습니다:

In [6]:
chart = alt.Chart(df)

지금까지 `Chart` 객체를 정의하고 위에서 생성한 간단한 데이터 프레임을 전달했습니다. 아직 차트에 데이터로 무엇을 *하라*고 지시하지는 않았습니다.

## 마크와 인코딩 (Marks and Encodings)

차트 객체가 준비되면 이제 데이터를 어떻게 시각화할지 지정할 수 있습니다. 먼저 데이터를 나타내는 데 사용할 그래픽 *마크(mark)* (기하학적 모양)의 종류를 지정합니다. `Chart.mark_*` 메서드를 사용하여 차트 객체의 `mark` 속성을 설정할 수 있습니다.

예를 들어, `Chart.mark_point()`를 사용하여 데이터를 점으로 표시할 수 있습니다:

In [7]:
alt.Chart(df).mark_point()

alt.Chart(...)

여기서 렌더링은 데이터 세트의 행당 하나의 점으로 구성되며, 아직 점의 위치를 지정하지 않았기 때문에 모두 서로 겹쳐서 플로팅됩니다.

점들을 시각적으로 분리하기 위해 다양한 *인코딩 채널(encoding channels)* 또는 줄여서 *채널(channels)*을 데이터 세트의 필드에 매핑할 수 있습니다. 예를 들어, 데이터의 `city` 필드를 점의 y축 위치를 나타내는 `y` 채널을 사용하여 *인코딩*할 수 있습니다. 이를 지정하려면 `encode` 메서드를 사용합니다:

In [8]:
alt.Chart(df).mark_point().encode(
  y='city',
)

alt.Chart(...)

`encode()` 메서드는 필드 이름을 통해 접근되는 데이터 세트의 필드에 인코딩 채널(`x`, `y`, `color`, `shape`, `size` 등) 간의 키-값 매핑을 구축합니다. Pandas 데이터 프레임의 경우, Altair는 매핑된 열에 적절한 데이터 유형을 자동으로 결정합니다. 이 경우 순서가 없는 범주형 값을 나타내는 *명목형(nominal)* 유형입니다.

하나의 속성으로 데이터를 분리했지만, 여전히 각 범주 내에서 여러 점이 겹쳐 있습니다. `'precip'` 필드에 매핑된 `x` 인코딩 채널을 추가하여 더 분리해 보겠습니다:

In [9]:
alt.Chart(df).mark_point().encode(
    x='precip',
    y='city'
)

alt.Chart(...)

_서울은 강수량이 가장 적은 달과 가장 많은 달을 모두 보여줍니다!_

Altair는 `'precip'` 필드의 데이터 유형도 자동으로 추론하며, 이번에는 *정량적(quantitative)* 유형(즉, 실수값)으로 처리됩니다. 그리드 라인과 적절한 축 제목도 자동으로 추가되는 것을 볼 수 있습니다.

위에서는 키워드 인수(`x='precip'`)를 사용하여 키-값 쌍을 지정했습니다. 또한 Altair는 `alt.X('precip')` 구문을 사용하여 인코딩 정의를 위한 생성 메서드를 제공합니다. 이 대안은 나중에 이 노트북에서 보게 되겠지만 인코딩에 더 많은 매개변수를 제공하는 데 유용합니다.

In [10]:
alt.Chart(df).mark_point().encode(
    alt.X('precip'),
    alt.Y('city')
)

alt.Chart(...)

두 가지 스타일의 인코딩 지정 방식을 혼합해서 사용할 수 있습니다. 예를 들어 `x='precip', alt.Y('city')`도 `encode` 함수의 유효한 입력입니다.

위의 예에서 각 필드의 데이터 유형은 Pandas 데이터 프레임 내의 유형에 따라 자동으로 추론됩니다. 또한 필드 이름에 주석을 달아 Altair에 데이터 유형을 명시적으로 알려줄 수도 있습니다.

- `'b:N'`은 *명목형(nominal)* 유형(순서가 없는 범주형 데이터)을 나타냅니다.
- `'b:O'`는 *순서형(ordinal)* 유형(순위가 있는 데이터)을 나타냅니다.
- `'b:Q'`는 *정량적(quantitative)* 유형(의미 있는 크기를 가진 수치 데이터)을 나타냅니다.
- `'b:T'`는 *시계열(temporal)* 유형(날짜/시간 데이터)을 나타냅니다.

예를 들어, `alt.X('precip:N')`와 같이 사용합니다.

데이터 유형의 명시적 지정은 데이터가 외부 URL에서 Vega-Lite에 의해 직접 로드될 때(Pandas를 완전히 건너뜀) 또는 자동으로 추론된 유형과 다른 유형을 사용하고 싶을 때 필요합니다.

`precip`을 정량적 변수가 아닌 명목형 또는 순서형 변수로 취급하면 위의 차트에 어떤 일이 일어날까요? _위의 코드를 수정하여 확인해 보세요!_

데이터 유형과 인코딩 채널에 대해서는 [데이터 시각화 커리큘럼](https://github.com/uwdata/visualization-curriculum#data-visualization-curriculum)의 다음 노트북에서 더 자세히 살펴보겠습니다.

## 데이터 변환: 집계 (Aggregation)

데이터를 시각화하는 방식에 더 많은 유연성을 제공하기 위해 Altair에는 데이터 *집계(aggregation)*를 위한 기본 구문이 내장되어 있습니다. 예를 들어, 필드 이름과 함께 집계 함수를 지정하여 모든 값의 평균을 계산할 수 있습니다:

In [11]:
alt.Chart(df).mark_point().encode(
    x='average(precip)',
    y='city'
)

alt.Chart(...)

이제 각 x축 범주 내에서 해당 범주 내 값의 *평균*을 반영하는 단일 점을 볼 수 있습니다.

_서울이 정말 이 도시들 중 평균 강수량이 가장 낮을까요? (실제로 그렇습니다!) 하지만 이 플롯이 어떻게 오해를 불러일으킬 수 있을까요? 어떤 달이 포함되었나요? 무엇을 강수량으로 간주하나요?_

Altair는 `count`, `min` (최솟값), `max` (최댓값), `average`, `median`, `stdev` (표준 편차)를 포함한 다양한 집계 함수를 지원합니다. 나중에 집계, 정렬, 필터링 및 계산 공식을 사용한 새로운 파생 필드 생성을 포함하여 데이터 변환에 대해 자세히 살펴보겠습니다.

## 마크 유형 변경하기 (Changing the Mark Type)

집계된 값을 원형 점 대신 직사각형 막대로 표현하고 싶다고 가정해 보겠습니다. `Chart.mark_point`를 `Chart.mark_bar`로 교체하여 이를 수행할 수 있습니다:

In [12]:
alt.Chart(df).mark_bar().encode(
    x='average(precip)',
    y='city'
)

alt.Chart(...)

명목형 필드가 `y`축에 매핑되었기 때문에 가로 막대 차트가 생성되었습니다. 세로 막대 차트를 만들려면 `x`와 `y` 키워드를 바꾸기만 하면 됩니다.

In [13]:
alt.Chart(df).mark_bar().encode(
    x='city',
    y='average(precip)'
)

alt.Chart(...)

## 시각화 사용자 정의하기 (Customizing a Visualization)

기본적으로 Altair / Vega-Lite는 시각화의 속성에 대해 몇 가지 선택을 하지만, 시각화의 모양을 사용자 정의하는 메서드를 사용하여 이를 변경할 수 있습니다. 예를 들어, 채널 클래스의 `axis` 속성을 사용하여 축 제목을 지정할 수 있고, `scale` 속성을 사용하여 스케일 속성을 수정할 수 있으며, `Chart.mark_*` 메서드의 `color` 키워드를 유효한 [CSS 색상 문자열](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)로 설정하여 마킹의 색상을 지정할 수 있습니다:

In [14]:
alt.Chart(df).mark_point(color='firebrick').encode(
  alt.X('precip', scale=alt.Scale(type='log'), axis=alt.Axis(title='로그 스케일 값')),
  alt.Y('city', axis=alt.Axis(title='범주')),
)

alt.Chart(...)

다음 모듈에서는 사용자 정의 차트를 만들기 위해 스케일, 축 및 범례에 사용할 수 있는 다양한 옵션을 살펴봅니다.

## 멀티 뷰 (Multiple Views)

위에서 보았듯이 Altair `Chart` 객체는 단일 마크 유형이 있는 플롯을 나타냅니다. 여러 차트나 레이어가 포함된 더 복잡한 다이어그램은 어떨까요? Altair는 일련의 *뷰 구성(view composition)* 연산자를 사용하여 여러 차트 정의를 가져와 결합하여 더 복잡한 뷰를 생성할 수 있습니다.

시작점으로 제조 연도별 평균 연비를 보여주는 선 차트로 자동차 데이터 세트를 플로팅해 보겠습니다:

In [15]:
alt.Chart(cars).mark_line().encode(
    alt.X('Year'),
    alt.Y('average(Miles_per_Gallon)')
)

alt.Chart(...)

이 플롯을 보완하기 위해 각 평균 데이터 포인트에 `circle` 마크를 추가하고 싶을 수 있습니다. (`circle` 마크는 채워진 원을 사용하는 `point` 마크의 편리한 약어입니다.)

먼저 각 차트를 별도로 정의하는 것부터 시작할 수 있습니다. 먼저 선 플롯을 정의한 다음 산점도를 정의합니다. 그런 다음 `layer` 연산자를 사용하여 두 차트를 레이어드 차트로 결합할 수 있습니다. 여기서는 레이어링을 호출하기 위해 약어인 `+` (더하기) 연산자를 사용합니다.

In [16]:
line = alt.Chart(cars).mark_line().encode(
    alt.X('Year'),
    alt.Y('average(Miles_per_Gallon)')
)

point = alt.Chart(cars).mark_circle().encode(
    alt.X('Year'),
    alt.Y('average(Miles_per_Gallon)')
)

line + point

alt.LayerChart(...)

이전 차트 정의를 *재사용*하고 *수정*하여 이 차트를 만들 수도 있습니다! 차트를 완전히 새로 쓰는 대신 선 차트에서 시작하여 `mark_point` 메서드를 호출하여 다른 마크 유형을 가진 새로운 차트 정의를 생성할 수 있습니다.

In [17]:
mpg = alt.Chart(cars).mark_line().encode(
    alt.X('Year'),
    alt.Y('average(Miles_per_Gallon)')
)

mpg + mpg.mark_circle()

alt.LayerChart(...)

<em>(선 위에 점을 배치해야 하는 경우가 매우 흔하기 때문에, `line` 마크에는 새로운 레이어를 생성해 주는 약어도 포함되어 있습니다. `mark_line` 메서드에 `point=True` 인수를 추가해 보세요!)</em>

이제 이 차트를 시간 경과에 따른 평균 마력과 같은 다른 플롯과 함께 보고 싶다면 어떻게 해야 할까요?

*연결(concatenation)* 연산자를 사용하여 여러 차트를 가로 또는 세로로 나란히 배치할 수 있습니다. 여기서는 `|` (파이프) 연산자를 사용하여 두 차트를 가로로 연결해 보겠습니다.

In [18]:
hp = alt.Chart(cars).mark_line().encode(
    alt.X('Year'),
    alt.Y('average(Horsepower)')
)

(mpg + mpg.mark_circle()) | (hp + hp.mark_circle())

alt.HConcatChart(...)

_이 데이터 세트에서 1970년대와 80년대 초반에 걸쳐 평균 연비는 향상된 반면 평균 마력은 감소했음을 알 수 있습니다._

나중에 다룰 노트북에서는 레이어링과 연결뿐만 아니라 데이터를 하위 플롯으로 나누기 위한 `facet` 연산자와 템플릿에서 연결된 차트를 간결하게 생성하기 위한 `repeat` 연산자를 포함한 *뷰 구성(view composition)*에 집중할 것입니다.

## 상호작용 (Interactivity)

기본적인 플로팅과 뷰 구성 외에도 Altair와 Vega-Lite의 가장 흥미로운 기능 중 하나는 상호작용 지원입니다.

팬(panning)과 줌(zooming)을 지원하는 간단한 대화형 플롯을 만들려면 `Chart` 객체의 `interactive()` 메서드를 호출하면 됩니다. 아래 차트에서 클릭하고 드래그하여 *이동(pan)*하거나 마우스 휠을 사용하여 *확대/축소(zoom)*해 보세요:

In [19]:
alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()

alt.Chart(...)

마우스를 올렸을 때 더 자세한 정보를 제공하기 위해 `tooltip` 인코딩 채널을 사용할 수 있습니다:

In [20]:
alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin'] # 툴팁에 이름과 원산지 표시
).interactive()

alt.Chart(...)

연결된 차트 및 교차 필터링과 같은 더 복잡한 상호작용을 위해 Altair는 대화형 선택을 정의한 다음 이를 차트의 구성 요소에 바인딩하기 위한 *선택(selection)* 추상화를 제공합니다. 이에 대해서는 나중에 다른 노트북에서 자세히 다룰 것입니다.

아래는 더 복잡한 예시입니다. 상단의 히스토그램은 연도별 자동차 수를 보여주며, 대화형 선택을 사용하여 마력 대 연비를 보여주는 하단 산점도의 점 투명도를 수정합니다.

_상단 차트에서 영역을 드래그하여 하단 차트의 점에 어떤 영향을 미치는지 확인해 보세요. 코드를 살펴보면서 **아직 이해가 안 가는 부분이 있더라도 걱정하지 마세요!** 이것은 야심찬 예시일 뿐이며, 여러 노트북을 거치면서 필요한 모든 세부 사항을 채워나갈 것입니다._

In [21]:
# x축 인코딩에 대한 간격 선택(interval selection) 생성
brush = alt.selection_interval(encodings=['x'])

# brush에 따라 불투명도 결정
opacity = alt.condition(brush, alt.value(0.9), alt.value(0.1))

# 연도별 자동차 수에 대한 개요 히스토그램
# 시간에 따른 자동차를 선택하기 위해 간격 브러시 추가
overview = alt.Chart(cars).mark_bar().encode(
    alt.X('Year:O', timeUnit='year', # 연도 단위를 추출하고 서수형(ordinal)으로 처리
      axis=alt.Axis(title=None, labelAngle=0) # 제목 없음, 레이블 각도 0
    ),
    alt.Y('count()', title=None), # 개수, 축 제목 없음
    opacity=opacity
).add_selection(
    brush      # 차트에 간격 브러시 선택 추가
).properties(
    width=400, # 차트 너비를 400 픽셀로 설정
    height=50  # 차트 높이를 50 픽셀로 설정
)

# 마력 대 연비에 대한 상세 산점도
# 브러시 선택에 따라 점의 불투명도 조절
detail = alt.Chart(cars).mark_point().encode(
    alt.X('Horsepower'),
    alt.Y('Miles_per_Gallon'),
    # 브러시 선택에 따라 불투명도 설정
    opacity=opacity
).properties(width=400) # 첫 번째 차트와 일치하도록 차트 너비 설정

# '&' 연산자를 사용하여 차트를 수직으로 연결(vconcat)
overview & detail

alt.VConcatChart(...)

## 여담: JSON 출력 검사하기 (Examining the JSON Output)

Vega-Lite에 대한 Python API로서 Altair의 주요 목적은 플롯 사양을 Vega-Lite 스키마를 준수하는 JSON 문자열로 변환하는 것입니다. `Chart.to_json` 메서드를 사용하여 Altair가 내보내고 Vega-Lite로 보내는 JSON 사양을 검사할 수 있습니다:

In [22]:
chart = alt.Chart(df).mark_bar().encode(
    x='average(precip)',
    y='city',
)
print(chart.to_json())

{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.8.1.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-fdfbb22e8e0e89f6556d8a3b434b0c97"
  },
  "datasets": {
    "data-fdfbb22e8e0e89f6556d8a3b434b0c97": [
      {
        "city": "서울",
        "month": "4월",
        "precip": 2.68
      },
      {
        "city": "서울",
        "month": "8월",
        "precip": 0.87
      },
      {
        "city": "서울",
        "month": "12월",
        "precip": 5.31
      },
      {
        "city": "부산",
        "month": "4월",
        "precip": 3.94
      },
      {
        "city": "부산",
        "month": "8월",
        "precip": 4.13
      },
      {
        "city": "부산",
        "month": "12월",
        "precip": 3.58
      },
      {
        "city": "제주",
        "month": "4월",
        "precip": 3.62
      },
      {
        "city": "제주",
        "month": "8월",
        "precip": 3.98
      },
      {
        "city": "제주",
        "month": "12월",
        "precip": 2.56
      }
    ]
  },
  "encoding": {
    "x": {
      "aggregate": "average",
      "field": "precip",
      "type": "quantitative"
    },
    "y": {
      "field": "city",
      "type": "nominal"
    }
  },
  "mark": "bar"
}

여기서 `encode(x='average(precip)')`가 `field` 이름, 데이터 `type`, `aggregate` 필드를 포함하는 JSON 구조로 확장된 것을 확인할 수 있습니다. `encode(y='city')` 문도 비슷하게 확장되었습니다.

앞서 보았듯이 Altair의 약칭 구문에는 필드 유형을 지정하는 방법도 포함되어 있습니다:

In [23]:
x = alt.X('average(precip):Q')
print(x.to_json())

{
  "aggregate": "average",
  "field": "precip",
  "type": "quantitative"
}

이 약칭은 속성 이름을 하나씩 나열하는 것과 동일합니다:

In [24]:
x = alt.X(aggregate='average', field='precip', type='quantitative')
print(x.to_json())

{
  "aggregate": "average",
  "field": "precip",
  "type": "quantitative"
}

## 시각화 게시하기 (Publishing a Visualization)

데이터를 시각화한 후에는 웹의 어딘가에 게시하고 싶을 수 있습니다. 이는 [vega-embed JavaScript 패키지](https://github.com/vega/vega-embed)를 사용하여 간단하게 수행할 수 있습니다. `Chart.save` 메서드를 사용하여 모든 차트에 대해 독립 실행형 HTML 문서의 간단한 예를 생성할 수 있습니다.

```python
chart = alt.Chart(df).mark_bar().encode(
    x='average(precip)',
    y='city',
)
chart.save('chart.html')
```


기본 HTML 템플릿은 다음과 같은 출력을 생성하며, 여기서 `Chart.to_json`에 의해 생성된 플롯의 JSON 사양은 `spec` JavaScript 변수에 저장되어야 합니다.

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@4"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
  </head>
  <body>
  <div id="vis"></div>
  <script>
    (function(vegaEmbed) {
      var spec = {}; /* 차트 사양을 위한 JSON 출력 */
      var embedOpt = {"mode": "vega-lite"}; /* 임베딩 옵션 */

      function showError(el, error){
          el.innerHTML = ('<div style="color:red;">'
                          + '<p>JavaScript 오류: ' + error.message + '</p>'
                          + "<p>이것은 일반적으로 차트 사양에 오타가 있음을 의미합니다. "
                          + "전체 추적은 자바스크립트 콘솔을 확인하세요.</p>"
                          + '</div>');
          throw error;
      }
      const el = document.getElementById('vis');
      vegaEmbed("#vis", spec, embedOpt)
        .catch(error => showError(el, error));
    })(vegaEmbed);
  </script>
</body>
</html>
 ```

`Chart.save` 메서드는 이러한 HTML 출력을 파일로 저장하는 편리한 방법을 제공합니다. Altair/Vega-Lite 임베딩에 대한 자세한 정보는 [vega-embed 프로젝트 문서](https://github.com/vega/vega-embed)를 참조하세요.

## 다음 단계 (Next Steps)

🎉 축하합니다! Altair 소개를 완료했습니다. 다음 노트북에서는 Altair의 데이터 유형, 그래픽 마크 및 시각적 인코딩 채널 모델을 사용하여 시각화를 만드는 과정을 더 자세히 살펴보겠습니다.